#+TITLE: EST-25134: Introducci贸n Estad铆stica INMEGEN
#+AUTHOR: Diego Arturo Vel谩zquez Trejo
#+EMAIL:  velazquez@ciencias.unam.mx
#+DATE: ~Primavera 2023~
:REVEAL_PROPERTIES:
#+LANGUAGE: es
#+OPTIONS: num:nil toc:nil timestamp:nil
#+REVEAL_EXTRA_CSS: ./notas/mods.css
#+REVEAL_THEME: night
#+REVEAL_SLIDE_NUMBER: t
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Aprendizaje Estad铆stico">
#+REVEAL_INIT_OPTIONS: width:1600, height:900, margin:.2
#+REVEAL_PLUGINS: (notes)
:END:
#+STARTUP: showall
#+EXCLUDE_TAGS: toc github latex



    
* Introducci贸n                                                       :github:

La estad铆stica es una disciplina esencial en el an谩lisis y la interpretaci贸n de datos en una amplia gama de disciplinas. 
En el Curso de Estad铆stica B谩sica, exploraremos los conceptos clave que permiten describir, analizar e inferir informaci贸n a partir de datos. 
Desde la identificaci贸n y clasificaci贸n de variables hasta la aplicaci贸n de pruebas de hip贸tesis y an谩lisis de distribuciones, este curso 
proporcionar谩 las bases para comprender la estad铆stica y su importancia en la toma de decisiones informadas. A lo largo de nuestras sesiones, 
aprenderemos c贸mo utilizar herramientas como R para realizar c谩lculos y crear visualizaciones que nos ayuden a comunicar de manera efectiva los 
resultados de nuestras an谩lisis. Ya sea que seas nuevo en la estad铆stica o busques consolidar tus conocimientos, este curso te brindar谩 las habilidades 
necesarias para trabajar con datos de manera confiable y significativa.

* Objetivo

El objetivo principal de este curso es proporcionar a los participantes una introducci贸n s贸lida y accesible a los conceptos 
fundamentales de la estad铆stica. A trav茅s de una combinaci贸n de teor铆a y aplicaciones pr谩cticas, los estudiantes adquirir谩n las 
herramientas necesarias para comprender, analizar y presentar datos de manera efectiva. 
Desde la comprensi贸n de las variables y su relaci贸n hasta el uso de pruebas estad铆sticas y t茅cnicas de inferencia, este curso 
sentar谩 las bases para una comprensi贸n s贸lida de la estad铆stica y su aplicaci贸n en diversos campos.



#+REVEAL: split

#+begin_src bash :exports results :results org :eval never

tree -L 1 -d 

#+end_src

#+RESULTS:
#+begin_src org
.
 docs       # Handouts con las notas de clase (pdf).
 images     # Material visual de apoyo (png).
 notas      
 renv       # Archivos de estructura de ambiente (R).
 rscripts   # Codigo de R para seguir la clase.

5 directories
#+end_src

* Horarios

El curso ser谩 los d铆as Jueves de 10:00am a 11:00am. 

* Ambiente de trabajo

El curso es agn贸stico al lenguaje de programaci贸n. Sin embargo, las notas y el
material estar谩 construido a partir de [[https://www.r-project.org/][R]]. En particular utilizaremos [[https://www.tidymodels.org/][tidymodels]]
como herramienta de programaci贸n dentro de ~R~ pues ofrece una ambiente unificado
de distintas librer铆as enfocadas en modelos predictivos. Adem谩s, es una
herramienta que representa muy bien la filosof铆a del curso. 

#+REVEAL: split
El ambiente de trabajo est谩 configurado para tener un espacio ~reproducible~. Es decir, independiente del 
sistema operativo unificaremos versiones para poder trabajar. Esto lo logramos con las siguientes herramientas 
(las menciono pero no espero que tengan familiaridad, a lo largo del curso veremos c贸mo utilizarlas).

** Ambiente de desarrollo gr谩fico integrado (IDE)

Se sugiere utilizar +[[https://www.rstudio.com/products/rstudio/download/][Rstudio]]+ =Visual Studio Code= para poder trabajar en sus
proyectos y sus tareas. En particular, el material de clase ser谩 editado en [[https://www.gnu.org/software/emacs/][GNU
Emacs]] a trav茅s de =orgfiles= (archivos con sufijo ~.org~) pero pueden ser
visualizados en ~Github~.

** Configuraci贸n ~R~

Utilizaremos ~renv~ para mantener actualizada las herramientas de ~R~ junto con el
contenido del curso. En la carpeta =notas= se encuentran los archivos de
requerimientos (=renv.lock=) con el que podr谩n usar los archivos que se vayan
decantando en la carpeta =rscripts=. A煤n asi, la configuraci贸n se ir谩 construyendo
en los ejercicios de tarea que vayamos utilizando en el curso.

#+REVEAL: split

*Nota*: Es necesario tener instalada la versi贸n ~4.2.1~ de ~R~ para tener la mejor
compatibilidad con el c贸digo del curso.

** Gesti贸n de librer铆as de R: ~renv~

Se recomienda escribir en el archivo =~/.Renviron= la siguiente l铆nea lo cual
mantendr谩 el cache de ~renv~ en un lugar centralizado

#+begin_src conf :tangle ~/.Renviron :mkdirp yes
  RENV_PATHS_ROOT=~/.renv
#+end_src

** Ambiente /Dockerizado/

Mi idea de ambiente computacional es el que se puede reproducir en cualquier
sistema operativo. Para esto ~Docker~ es la herramienta ideal y el uso de los
~Codespaces~ de GitHub ha resultado incre铆ble para una soluci贸n dentro de un
谩mbito educativo.

#+REVEAL: split
Para la imagen ~agarbuno/aprendizaje~ consideren que: 
1) El /tag/ ~notas~ basado en una distribuci贸n linux en una emulaci贸n con un
   procesador ~Intel~, tiene la configuraci贸n m铆nima necesaria para poder
   reproducir el ambiente de c贸mputo para poder ejecutar el material del curso

#+REVEAL: split
Esto no les puede decir mucho, pero b谩sicamente con el combo 
~Docker~ + ~Visual Code Studio~, 隆tod@s tenemos la misma computadora para trabajar! ゲ.  
Y si lo quieren correr en la nube entonces: ~Docker~ + ~Visual Code Studio~ + ~Github Codespaces~ ゲ $\times 10^{78}$.

#+REVEAL: split
~Importante~: No espero que sepan reproducir ustedes la configuraci贸n del ambiente de 
trabajo. Si les interesa podemos organizar una sesi贸n para discutir esto a profundidad.
Lo importante es que lo sepan utilizar en su computadora o en un explorador de internet.
Esto es, que pueden utilizarlo para las pr谩cticas del curso. 
