#+TITLE: EST-25134: Introducción Estadística INMEGEN
#+AUTHOR: Diego Arturo Velázquez Trejo
#+EMAIL:  velazquez@ciencias.unam.mx
#+DATE: ~Primavera 2023~
:REVEAL_PROPERTIES:
#+LANGUAGE: es
#+OPTIONS: num:nil toc:nil timestamp:nil
#+REVEAL_EXTRA_CSS: ./notas/mods.css
#+REVEAL_THEME: night
#+REVEAL_SLIDE_NUMBER: t
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Aprendizaje Estadístico">
#+REVEAL_INIT_OPTIONS: width:1600, height:900, margin:.2
#+REVEAL_PLUGINS: (notes)
:END:
#+STARTUP: showall
#+EXCLUDE_TAGS: toc github latex



    
* Introducción                                                       :github:

Este es el repositorio con el contenido del curso en *Aprendizaje Estadístico*
ofrecido a estudiantes de semestres avanzados en las licenciaturas de
matemáticas aplicadas, ciencia de datos, actuaría, economía, etc.

* Objetivo

El Aprendizaje Estadístico trata de cómo establecer reglas de asociación al
observar un conjunto de datos. En este curso estudiaremos las ideas
fundamentales detrás de las técnicas de aprendizaje modernas e incorporaremos
conceptos familiares de estadística. El libro de texto será [[cite:James2021]] y
lo complementaremos con el enfoque de [[cite:Kuhn2013]]. Se estudiarán, además,
técnicas estadísticas modernas aplicadas a modelado predictivo por medio de
lecturas que acompañaran el curso.

#+REVEAL: split

#+begin_src bash :exports results :results org :eval never

tree -L 1 -d 

#+end_src

#+RESULTS:
#+begin_src org
.
├── docs       # Handouts con las notas de clase (pdf).
├── images     # Material visual de apoyo (png).
├── notas      
├── renv       # Archivos de estructura de ambiente (R).
└── rscripts   # Codigo de R para seguir la clase.

5 directories
#+end_src

* Horarios

El curso será los días Jueves de 10:00am a 11:00am. 

* Ambiente de trabajo

El curso es agnóstico al lenguaje de programación. Sin embargo, las notas y el
material estará construido a partir de [[https://www.r-project.org/][R]]. En particular utilizaremos [[https://www.tidymodels.org/][tidymodels]]
como herramienta de programación dentro de ~R~ pues ofrece una ambiente unificado
de distintas librerías enfocadas en modelos predictivos. Además, es una
herramienta que representa muy bien la filosofía del curso. 

#+REVEAL: split
El ambiente de trabajo está configurado para tener un espacio ~reproducible~. Es decir, independiente del 
sistema operativo unificaremos versiones para poder trabajar. Esto lo logramos con las siguientes herramientas 
(las menciono pero no espero que tengan familiaridad, a lo largo del curso veremos cómo utilizarlas).

** Ambiente de desarrollo gráfico integrado (IDE)

Se sugiere utilizar +[[https://www.rstudio.com/products/rstudio/download/][Rstudio]]+ =Visual Studio Code= para poder trabajar en sus
proyectos y sus tareas. En particular, el material de clase será editado en [[https://www.gnu.org/software/emacs/][GNU
Emacs]] a través de =orgfiles= (archivos con sufijo ~.org~) pero pueden ser
visualizados en ~Github~.

** Configuración ~R~

Utilizaremos ~renv~ para mantener actualizada las herramientas de ~R~ junto con el
contenido del curso. En la carpeta =notas= se encuentran los archivos de
requerimientos (=renv.lock=) con el que podrán usar los archivos que se vayan
decantando en la carpeta =rscripts=. Aún asi, la configuración se irá construyendo
en los ejercicios de tarea que vayamos utilizando en el curso.

#+REVEAL: split

*Nota*: Es necesario tener instalada la versión ~4.2.1~ de ~R~ para tener la mejor
compatibilidad con el código del curso.

** Gestión de librerías de R: ~renv~

Se recomienda escribir en el archivo =~/.Renviron= la siguiente línea lo cual
mantendrá el cache de ~renv~ en un lugar centralizado

#+begin_src conf :tangle ~/.Renviron :mkdirp yes
  RENV_PATHS_ROOT=~/.renv
#+end_src

** Ambiente /Dockerizado/

Mi idea de ambiente computacional es el que se puede reproducir en cualquier
sistema operativo. Para esto ~Docker~ es la herramienta ideal y el uso de los
~Codespaces~ de GitHub ha resultado increíble para una solución dentro de un
ámbito educativo.

#+REVEAL: split
Para la imagen ~agarbuno/aprendizaje~ consideren que: 
1) El /tag/ ~notas~ basado en una distribución linux en una emulación con un
   procesador ~Intel~, tiene la configuración mínima necesaria para poder
   reproducir el ambiente de cómputo para poder ejecutar el material del curso

#+REVEAL: split
Esto no les puede decir mucho, pero básicamente con el combo 
~Docker~ + ~Visual Code Studio~, ¡tod@s tenemos la misma computadora para trabajar! 🥲.  
Y si lo quieren correr en la nube entonces: ~Docker~ + ~Visual Code Studio~ + ~Github Codespaces~ 🥲 $\times 10^{78}$.

#+REVEAL: split
~Importante~: No espero que sepan reproducir ustedes la configuración del ambiente de 
trabajo. Si les interesa podemos organizar una sesión para discutir esto a profundidad.
Lo importante es que lo sepan utilizar en su computadora o en un explorador de internet.
Esto es, que pueden utilizarlo para las prácticas del curso. 
